development:
  password: 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
  theme_id: 114093621409
  store: goats-theme.myshopify.com
  directory: build
  ignore_files:
    - config/settings_data.json

    
staging:
  password: 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
  theme_id: 107149656225
  store: goats-theme.myshopify.com
  directory: build
  ignore_files:
    - config/settings_data.json


production:
  password: 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
  theme_id: 107149656225
  store: https://goats-theme.myshopify.com
  directory: build
  ignore_files:
    - config/settings_data.json


    
