development:
  password: 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
  theme_id: 107054137494
  store: goats-base-theme.myshopify.com
  directory: build
  ignore_files:
    - config/settings_data.json

    
staging:
  password: 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
  theme_id: 107054137494
  store: goats-base-theme.myshopify.com
  directory: build
  ignore_files:
    - config/settings_data.json


production:
  password: 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
  theme_id: 107054137494
  store: goats-base-theme.myshopify.com
  directory: build
  ignore_files:
    - config/settings_data.json


    
